// Generated by scripts/protocol_generate.py. DO NOT EDIT.
export const PROTOCOL_VERSION = "1.0" as const;
export const PROTOCOL_SCHEMA = "zekam-app-server-protocol/v1" as const;
export type ProtocolMethod = "experimental/session-fork.prepare" | "initialize" | "initialized" | "notifications/replay" | "project/read" | "server/notification" | "server/status" | "session/read" | "work/read";
export type AppNotificationPayload = { readonly "schema": "zekam-app-notification/v1"; readonly "event_id": string; readonly "sequence": number; readonly "previous_digest": (string) | (null); readonly "event_type": string; readonly "payload": { readonly [key: string]: unknown; }; readonly "occurred_at": string; readonly "grants_authority": false; readonly "event_digest": string; };
export type EmptyParams = {  };
export type ErrorResponse = { readonly "jsonrpc": "2.0"; readonly "id": (JsonRpcId) | (null); readonly "error": ProtocolError; };
export type ForkPrepareRequest = { readonly "jsonrpc": "2.0"; readonly "id": JsonRpcId; readonly "method": "experimental/session-fork.prepare"; readonly "params": EmptyParams; };
export type ForkPrepareResult = { readonly "schema": "zekam-session-fork-prepare/v1"; readonly "disposition": "prepare-only"; readonly "carries_authority": false; readonly "carries_lease": false; readonly "carries_receipt": false; readonly "read_only": true; readonly "grants_authority": false; };
export type FutureNotification = { readonly "jsonrpc": "2.0"; readonly "method": string; readonly "params": { readonly [key: string]: unknown; }; };
export type InitializeParams = { readonly "client_id": string; readonly "client_version": string; readonly "protocol_version": "1.0"; readonly "schema_bundle_digest": string; readonly "capabilities": ReadonlyArray<string>; readonly "experimental_methods": ReadonlyArray<string>; readonly "replay_cursor": (number) | (null); };
export type InitializeRequest = { readonly "jsonrpc": "2.0"; readonly "id": JsonRpcId; readonly "method": "initialize"; readonly "params": InitializeParams; };
export type InitializeResult = { readonly "schema": "zekam-app-server-protocol/v1"; readonly "connection_id": string; readonly "protocol_version": "1.0"; readonly "schema_bundle_digest": string; readonly "capabilities": ReadonlyArray<string>; readonly "experimental_methods": ReadonlyArray<string>; readonly "ingress_limit": number; readonly "outbound_limit": number; readonly "replay_limit": number; readonly "max_frame_bytes": number; readonly "read_only": true; readonly "grants_authority": false; };
export type InitializedNotification = { readonly "jsonrpc": "2.0"; readonly "method": "initialized"; readonly "params": EmptyParams; };
export type JsonRpcId = (string) | (number);
export type ProjectReadParams = { readonly "project_id": string; };
export type ProjectReadRequest = { readonly "jsonrpc": "2.0"; readonly "id": JsonRpcId; readonly "method": "project/read"; readonly "params": ProjectReadParams; };
export type ProtocolError = { readonly "code": number; readonly "message": string; readonly "data": ProtocolErrorData; };
export type ProtocolErrorData = { readonly "category": "parse-error" | "invalid-request" | "method-not-found" | "not-initialized" | "already-initialized" | "schema-mismatch" | "overloaded" | "policy-denied" | "experimental-not-enabled" | "cursor-expired"; readonly "retryable": boolean; readonly "grants_authority": false; readonly [key: string]: unknown; };
export type ProtocolNotification = (InitializedNotification) | (ServerNotification) | (FutureNotification);
export type ProtocolRequest = (InitializeRequest) | (StatusRequest) | (ReplayRequest) | (ProjectReadRequest) | (WorkReadRequest) | (SessionReadRequest) | (ForkPrepareRequest);
export type ProtocolResponse = (ResultResponse) | (ErrorResponse);
export type ReadResult = { readonly "schema": "zekam-app-read-projection/v1"; readonly "kind": "project" | "work" | "session"; readonly "reference": string; readonly "found": boolean; readonly "value": ({ readonly [key: string]: unknown; }) | (null); readonly "canonical_reread": true; readonly "read_only": true; readonly "grants_authority": false; };
export type ReplayParams = { readonly "after_sequence": number; readonly "limit": number; };
export type ReplayRequest = { readonly "jsonrpc": "2.0"; readonly "id": JsonRpcId; readonly "method": "notifications/replay"; readonly "params": ReplayParams; };
export type ReplayResult = { readonly "schema": "zekam-notification-replay/v1"; readonly "events": ReadonlyArray<AppNotificationPayload>; readonly "next_cursor": number; readonly "connection_cursor": number; readonly "head_cursor": number; readonly "read_only": true; readonly "grants_authority": false; };
export type ResultResponse = { readonly "jsonrpc": "2.0"; readonly "id": JsonRpcId; readonly "result": (InitializeResult) | (StatusResult) | (ReplayResult) | (ReadResult) | (ForkPrepareResult); };
export type ServerNotification = { readonly "jsonrpc": "2.0"; readonly "method": "server/notification"; readonly "params": AppNotificationPayload; };
export type SessionReadParams = { readonly "session_id": string; readonly "limit": number; };
export type SessionReadRequest = { readonly "jsonrpc": "2.0"; readonly "id": JsonRpcId; readonly "method": "session/read"; readonly "params": SessionReadParams; };
export type StatusRequest = { readonly "jsonrpc": "2.0"; readonly "id": JsonRpcId; readonly "method": "server/status"; readonly "params": EmptyParams; };
export type StatusResult = { readonly "schema": "zekam-app-server-status/v1"; readonly "connection_id": string; readonly "phase": "ready"; readonly "client_id": string; readonly "capabilities": ReadonlyArray<string>; readonly "replay_cursor": number; readonly "notification_head": number; readonly "read_only": true; readonly "grants_authority": false; };
export type WorkReadParams = { readonly "work_item_id": string; };
export type WorkReadRequest = { readonly "jsonrpc": "2.0"; readonly "id": JsonRpcId; readonly "method": "work/read"; readonly "params": WorkReadParams; };
export type ProtocolDocument = (ProtocolRequest) | (ProtocolNotification) | (ProtocolResponse);
export interface JsonRpcRequest<P extends Record<string, unknown> = Record<string, unknown>> {
  readonly jsonrpc: "2.0";
  readonly id: JsonRpcId;
  readonly method: ProtocolMethod;
  readonly params: P;
}
export interface JsonRpcNotification<P extends Record<string, unknown> = Record<string, unknown>> {
  readonly jsonrpc: "2.0";
  readonly method: ProtocolMethod;
  readonly params: P;
}
export interface JsonRpcError {
  readonly code: number;
  readonly message: string;
  readonly data: ProtocolErrorData & Record<string, unknown>;
}
export type JsonRpcResponse<R = unknown> =
  | { readonly jsonrpc: "2.0"; readonly id: JsonRpcId; readonly result: R }
  | { readonly jsonrpc: "2.0"; readonly id: JsonRpcId | null; readonly error: JsonRpcError };
