"""Deterministic generation for the versioned App Server protocol SDK."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from zekam.domain.app_server_protocol import (
    PROTOCOL_SCHEMA,
    PROTOCOL_VERSION,
    schema_bundle_digest,
)
from zekam.domain.app_server_protocol import protocol_schema_bundle as schema_bundle
from zekam.domain.canonical import digest

GENERATED_RESOURCE_NAMES = (
    "schema-bundle.json",
    "client-types.ts",
    "protocol-version.json",
    "event-methods.json",
    "compatibility-matrix.json",
    "SHA256SUMS",
)


def _json(document: Any) -> str:
    return json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def _event_methods(schema: dict[str, Any]) -> list[str]:
    methods: set[str] = set()

    def visit(value: Any) -> None:
        if isinstance(value, dict):
            method = value.get("properties", {}).get("method", {}).get("const")
            if isinstance(method, str):
                methods.add(method)
            for child in value.values():
                visit(child)
        elif isinstance(value, list):
            for child in value:
                visit(child)

    visit(schema)
    return sorted(methods)


def _ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", maxsplit=1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    for keyword in ("anyOf", "oneOf"):
        if keyword in schema:
            return " | ".join(f"({_ts_type(item)})" for item in schema[keyword])
    if "allOf" in schema:
        return " & ".join(f"({_ts_type(item)})" for item in schema["allOf"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(_ts_type({"type": item}) for item in kind)
    if not isinstance(kind, str):
        return "unknown"
    if kind == "array":
        return f"ReadonlyArray<{_ts_type(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        fields = [
            f"readonly {json.dumps(name)}{'?' if name not in required else ''}: {_ts_type(value)};"
            for name, value in schema.get("properties", {}).items()
        ]
        additional = schema.get("additionalProperties")
        if additional is True:
            fields.append("readonly [key: string]: unknown;")
        elif isinstance(additional, dict):
            fields.append(f"readonly [key: string]: {_ts_type(additional)};")
        return "{ " + " ".join(fields) + " }"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def _typescript(schema: dict[str, Any], methods: list[str]) -> str:
    literals = " | ".join(json.dumps(method) for method in methods)
    definitions = "\n".join(
        f"export type {name} = {_ts_type(value)};"
        for name, value in sorted(schema.get("$defs", {}).items())
    )
    document = _ts_type({key: value for key, value in schema.items() if key != "$defs"})
    return f"""// Generated by scripts/protocol_generate.py. DO NOT EDIT.
export const PROTOCOL_VERSION = {json.dumps(PROTOCOL_VERSION)} as const;
export const PROTOCOL_SCHEMA = {json.dumps(PROTOCOL_SCHEMA)} as const;
export type ProtocolMethod = {literals};
{definitions}
export type ProtocolDocument = {document};
export interface JsonRpcRequest<P extends Record<string, unknown> = Record<string, unknown>> {{
  readonly jsonrpc: "2.0";
  readonly id: JsonRpcId;
  readonly method: ProtocolMethod;
  readonly params: P;
}}
export interface JsonRpcNotification<P extends Record<string, unknown> = Record<string, unknown>> {{
  readonly jsonrpc: "2.0";
  readonly method: ProtocolMethod;
  readonly params: P;
}}
export interface JsonRpcError {{
  readonly code: number;
  readonly message: string;
  readonly data: ProtocolErrorData & Record<string, unknown>;
}}
export type JsonRpcResponse<R = unknown> =
  | {{ readonly jsonrpc: "2.0"; readonly id: JsonRpcId; readonly result: R }}
  | {{ readonly jsonrpc: "2.0"; readonly id: JsonRpcId | null; readonly error: JsonRpcError }};
"""


def render_protocol_artifacts() -> dict[str, str]:
    """Render all generated resources without touching the filesystem."""
    schema = schema_bundle()
    methods = _event_methods(schema)
    artifacts = {
        "schema-bundle.json": _json(schema),
        "client-types.ts": _typescript(schema, methods),
        "protocol-version.json": _json(
            {
                "protocol_schema": PROTOCOL_SCHEMA,
                "protocol_version": PROTOCOL_VERSION,
                "schema_bundle_digest": schema_bundle_digest(),
            }
        ),
        "event-methods.json": _json(
            {
                "methods": methods,
                "protocol_version": PROTOCOL_VERSION,
                "schema": "zekam-protocol-event-methods/v1",
            }
        ),
        "compatibility-matrix.json": _json(
            {
                "entries": [
                    {
                        "compatibility": "exact-version",
                        "protocol_version": PROTOCOL_VERSION,
                        "schema_bundle_digest": schema_bundle_digest(),
                    }
                ],
                "schema": "zekam-protocol-compatibility-matrix/v1",
            }
        ),
    }
    checksums = "".join(
        f"{hashlib.sha256(content.encode('utf-8')).hexdigest()}  {name}\n"
        for name, content in sorted(artifacts.items())
    )
    return artifacts | {"SHA256SUMS": checksums}


def protocol_artifact_digest() -> str:
    """Return one canonical digest binding every generated byte sequence."""
    return digest(render_protocol_artifacts())


def generate_protocol_artifacts(output: Path, *, check: bool = False) -> bool:
    """Write resources or return whether an output directory is byte-exact."""
    rendered = render_protocol_artifacts()
    if check:
        return all(
            (output / name).is_file() and (output / name).read_text(encoding="utf-8") == content
            for name, content in rendered.items()
        )
    output.mkdir(parents=True, exist_ok=True)
    for name, content in rendered.items():
        (output / name).write_text(content, encoding="utf-8", newline="\n")
    return True
