-- Persisted child runtime residency, safe eviction/reload and dead-child cleanup.

-- A dead runtime without verified usage evidence cannot release the graph reservation.
-- Extend the assignment state machine with a non-terminal recovery state while preserving
-- the original anonymous constraint names generated by PostgreSQL.
do $$
declare item record;
begin
  for item in
    select conname,pg_get_constraintdef(oid) definition
      from pg_constraint
     where conrelid='agents.assignment'::regclass and contype='c'
  loop
    if item.definition like '%status = ANY%ready%active%blocked%cancelled%'
       or item.definition like '%status IN%ready%active%blocked%cancelled%' then
      execute format('alter table agents.assignment drop constraint %I',item.conname);
    elsif item.definition like '%terminal_at%status = ANY%completed%failed%cancelled%'
       or item.definition like '%terminal_at%status IN%completed%failed%cancelled%' then
      execute format('alter table agents.assignment drop constraint %I',item.conname);
    end if;
  end loop;
end $$;
alter table agents.assignment
  add constraint assignment_status_residency_check check (
    status in ('ready','active','completed','failed','blocked','cancelled','recovery-required')
  ),
  add constraint assignment_terminal_residency_check check (
    (status in ('completed','failed','cancelled'))=(terminal_at is not null)
  );

create table agents.assignment_runtime_snapshot (
  id uuid primary key,
  realm_id uuid not null,
  edge_id uuid not null,
  assignment_id uuid not null,
  execution_envelope_id uuid not null,
  role text not null,
  model_id text not null,
  provider_binding_id uuid not null,
  provider_binding_digest text not null,
  route_decision_id uuid not null,
  route_decision_digest text not null,
  environment_snapshot_digest text not null,
  permission_profile_digest text not null,
  config_effective_digest text not null,
  source_revision text not null,
  policy_digest text not null,
  snapshot_digest text not null,
  snapshot_body jsonb not null,
  grants_authority boolean not null default false,
  created_at timestamptz not null,
  unique(realm_id,id),unique(realm_id,edge_id),unique(realm_id,snapshot_digest),
  foreign key(realm_id,edge_id) references agents.spawn_edge(realm_id,id),
  foreign key(realm_id,assignment_id) references agents.assignment(realm_id,id),
  foreign key(realm_id,execution_envelope_id) references runtime.execution_envelope(realm_id,id),
  foreign key(realm_id,provider_binding_id)
    references models.provider_binding_snapshot(realm_id,id),
  foreign key(realm_id,route_decision_id) references models.model_route_decision(realm_id,id),
  foreign key(realm_id,environment_snapshot_digest)
    references runtime.execution_environment_snapshot(realm_id,snapshot_digest),
  check(btrim(role)<>'' and btrim(model_id)<>'' and btrim(source_revision)<>''),
  check(provider_binding_digest ~ '^sha256:[0-9a-f]{64}$'),
  check(route_decision_digest ~ '^sha256:[0-9a-f]{64}$'),
  check(environment_snapshot_digest ~ '^sha256:[0-9a-f]{64}$'),
  check(permission_profile_digest ~ '^sha256:[0-9a-f]{64}$'),
  check(config_effective_digest ~ '^sha256:[0-9a-f]{64}$'),
  check(policy_digest ~ '^sha256:[0-9a-f]{64}$'),
  check(snapshot_digest ~ '^sha256:[0-9a-f]{64}$' and not grants_authority)
);

create function agents.enforce_assignment_runtime_snapshot() returns trigger language plpgsql
security invoker set search_path=pg_catalog,agents,runtime,models as $$
declare edge record; declare envelope record; declare turn record; declare env record;
declare assignment record; declare binding record; declare route record; declare provider record;
begin
  select child_assignment_id,root_id,status into edge from agents.spawn_edge
    where realm_id=new.realm_id and id=new.edge_id;
  select role,status into assignment from agents.assignment
    where realm_id=new.realm_id and id=new.assignment_id;
  select assignment_id,run_id,role,model_id,provider_binding_id,provider_binding_digest,
    route_decision_id,route_decision_digest,source_revision,policy_digest,
    turn_execution_snapshot_id,created_at into envelope from runtime.execution_envelope
    where realm_id=new.realm_id and id=new.execution_envelope_id;
  select execution_environment_snapshot_digest,config_effective_digest into turn
    from runtime.turn_execution_snapshot
    where realm_id=new.realm_id and id=envelope.turn_execution_snapshot_id;
  select permission_profile_digest,config_effective_digest,source_revision,expires_at into env
    from runtime.execution_environment_snapshot
    where realm_id=new.realm_id and snapshot_digest=new.environment_snapshot_digest;
  select execution_environment_snapshot_digest into binding
    from agents.assignment_environment_binding
    where realm_id=new.realm_id and assignment_id=new.assignment_id;
  select d.status,d.primary_model_id,d.evidence_digest,target.expires_at into route
    from models.model_route_decision d join models.execution_target_snapshot target
      on target.realm_id=d.realm_id and target.id=d.execution_target_id
    where d.realm_id=new.realm_id and d.id=new.route_decision_id;
  select model_id,binding_digest,expires_at into provider from models.provider_binding_snapshot
    where realm_id=new.realm_id and id=new.provider_binding_id;
  if edge.child_assignment_id is distinct from new.assignment_id
    or edge.status in ('completed','failed','cancelled')
    or assignment.role is distinct from new.role
    or assignment.status in ('completed','failed','cancelled')
    or row(envelope.assignment_id,envelope.role,envelope.model_id,envelope.provider_binding_id,
      envelope.provider_binding_digest,envelope.route_decision_id,envelope.route_decision_digest,
      envelope.source_revision,envelope.policy_digest) is distinct from
      row(new.assignment_id,new.role,new.model_id,new.provider_binding_id,
      new.provider_binding_digest,new.route_decision_id,new.route_decision_digest,
      new.source_revision,new.policy_digest)
    or turn.execution_environment_snapshot_digest is distinct from new.environment_snapshot_digest
    or turn.config_effective_digest is distinct from new.config_effective_digest
    or row(env.permission_profile_digest,env.config_effective_digest,env.source_revision)
      is distinct from row(new.permission_profile_digest,new.config_effective_digest,
        new.source_revision)
    or env.expires_at<=new.created_at
    or envelope.created_at>new.created_at
    or binding.execution_environment_snapshot_digest is distinct from
      new.environment_snapshot_digest
    or row(route.status,route.primary_model_id,route.evidence_digest)
      is distinct from row('selected',new.model_id,new.route_decision_digest)
    or row(provider.model_id,provider.binding_digest)
      is distinct from row(new.model_id,new.provider_binding_digest)
    or provider.expires_at<=new.created_at or route.expires_at<=new.created_at
    or not exists(select 1 from agents.graph_root root join runtime.execution_run run
      on run.realm_id=root.realm_id and run.id=root.run_id
      where root.realm_id=new.realm_id and root.id=edge.root_id
        and run.id=envelope.run_id and run.state='active' and run.deadline>new.created_at
        and run.source_revision=new.source_revision and run.policy_digest=new.policy_digest) then
    raise exception 'assignment runtime snapshot canonical binding drift' using errcode='23514';
  end if;
  if models.capability_runtime_jsonb_digest(new.snapshot_body)<>new.snapshot_digest
    or (select count(*) from jsonb_object_keys(new.snapshot_body))<>19
    or new.snapshot_body->>'schema'<>'zekam-assignment-runtime-snapshot/v1'
    or new.snapshot_body->>'id'<>new.id::text
    or new.snapshot_body->>'realm_id'<>new.realm_id::text
    or new.snapshot_body->>'edge_id'<>new.edge_id::text
    or new.snapshot_body->>'assignment_id'<>new.assignment_id::text
    or new.snapshot_body->>'execution_envelope_id'<>new.execution_envelope_id::text
    or new.snapshot_body->>'role'<>new.role or new.snapshot_body->>'model_id'<>new.model_id
    or new.snapshot_body->>'provider_binding_id'<>new.provider_binding_id::text
    or new.snapshot_body->>'provider_binding_digest'<>new.provider_binding_digest
    or new.snapshot_body->>'route_decision_id'<>new.route_decision_id::text
    or new.snapshot_body->>'route_decision_digest'<>new.route_decision_digest
    or new.snapshot_body->>'environment_snapshot_digest'<>new.environment_snapshot_digest
    or new.snapshot_body->>'permission_profile_digest'<>new.permission_profile_digest
    or new.snapshot_body->>'config_effective_digest'<>new.config_effective_digest
    or new.snapshot_body->>'source_revision'<>new.source_revision
    or new.snapshot_body->>'policy_digest'<>new.policy_digest
    or (new.snapshot_body->>'created_at')::timestamptz<>new.created_at
    or (new.snapshot_body->>'grants_authority')::boolean then
    raise exception 'assignment runtime snapshot body/digest drift' using errcode='23514';
  end if;
  return new;
end $$;
create trigger assignment_runtime_snapshot_guard before insert
on agents.assignment_runtime_snapshot for each row
execute function agents.enforce_assignment_runtime_snapshot();

create table agents.runtime_residency (
  id uuid primary key,
  realm_id uuid not null,
  edge_id uuid not null,
  runtime_snapshot_id uuid not null,
  state text not null,
  generation integer not null default 1,
  runtime_session_ref text,
  last_seen_at timestamptz not null,
  state_changed_at timestamptz not null,
  dead_reason text,
  grants_authority boolean not null default false,
  created_at timestamptz not null,
  unique(realm_id,id),unique(realm_id,edge_id),
  foreign key(realm_id,edge_id) references agents.spawn_edge(realm_id,id),
  foreign key(realm_id,runtime_snapshot_id)
    references agents.assignment_runtime_snapshot(realm_id,id),
  check(state in ('loaded','idle','evicted','closing','dead')),
  check(generation>0 and last_seen_at>=created_at and state_changed_at>=created_at),
  check((state in ('loaded','idle','closing'))=(runtime_session_ref is not null)),
  check(runtime_session_ref is null or btrim(runtime_session_ref)<>''),
  check((state='dead')=(dead_reason is not null)),
  check(dead_reason is null or (btrim(dead_reason)<>'' and length(dead_reason)<=256)),
  check(not grants_authority)
);

create table agents.residency_event (
  id uuid primary key,
  realm_id uuid not null,
  residency_id uuid not null,
  edge_id uuid not null,
  sequence integer not null,
  previous_digest text,
  state text not null,
  generation integer not null,
  reason text,
  event_digest text not null,
  event_body jsonb not null,
  occurred_at timestamptz not null,
  grants_authority boolean not null default false,
  unique(realm_id,id),unique(realm_id,residency_id,sequence),unique(realm_id,event_digest),
  foreign key(realm_id,residency_id) references agents.runtime_residency(realm_id,id),
  foreign key(realm_id,edge_id) references agents.spawn_edge(realm_id,id),
  check(sequence>0 and generation>0),
  check(state in ('loaded','idle','evicted','closing','dead')),
  check((sequence=1)=(previous_digest is null)),
  check(previous_digest is null or previous_digest ~ '^sha256:[0-9a-f]{64}$'),
  check(event_digest ~ '^sha256:[0-9a-f]{64}$' and not grants_authority)
);

create table agents.reload_attempt (
  id uuid primary key,
  realm_id uuid not null,
  residency_id uuid not null,
  edge_id uuid not null,
  stored_snapshot_id uuid not null,
  current_environment_snapshot_digest text not null,
  current_route_decision_id uuid not null,
  current_provider_binding_id uuid not null,
  accepted boolean not null,
  reason text,
  resulting_generation integer not null,
  request_digest text not null,
  request_body jsonb not null,
  attempted_at timestamptz not null,
  grants_authority boolean not null default false,
  unique(realm_id,id),unique(realm_id,request_digest),
  foreign key(realm_id,residency_id) references agents.runtime_residency(realm_id,id),
  foreign key(realm_id,edge_id) references agents.spawn_edge(realm_id,id),
  foreign key(realm_id,stored_snapshot_id)
    references agents.assignment_runtime_snapshot(realm_id,id),
  foreign key(realm_id,current_environment_snapshot_digest)
    references runtime.execution_environment_snapshot(realm_id,snapshot_digest),
  foreign key(realm_id,current_route_decision_id)
    references models.model_route_decision(realm_id,id),
  foreign key(realm_id,current_provider_binding_id)
    references models.provider_binding_snapshot(realm_id,id),
  check((accepted and reason is null) or (not accepted and btrim(reason)<>'')),
  check(resulting_generation>0),
  check(request_digest ~ '^sha256:[0-9a-f]{64}$' and not grants_authority)
);

create function agents.append_residency_event(
  p_realm uuid,p_residency uuid,p_edge uuid,p_state text,p_generation integer,
  p_reason text,p_occurred timestamptz
) returns void language plpgsql security definer
set search_path=pg_catalog,agents,models as $$
declare previous record; declare event_id uuid:=gen_random_uuid(); declare body jsonb;
declare seq integer;
begin
  select sequence,event_digest,occurred_at into previous from agents.residency_event
    where realm_id=p_realm and residency_id=p_residency order by sequence desc limit 1;
  seq:=case when found then previous.sequence+1 else 1 end;
  if found and p_occurred<previous.occurred_at then
    raise exception 'residency event zamani geriye gidemez' using errcode='23514';
  end if;
  body:=jsonb_build_object('schema','zekam-agent-residency-event/v1','id',event_id::text,
    'realm_id',p_realm::text,'residency_id',p_residency::text,'edge_id',p_edge::text,
    'sequence',seq,'previous_digest',case when seq=1 then null else previous.event_digest end,
    'state',p_state,'generation',p_generation,'reason',p_reason,
    'occurred_at',runtime.environment_canonical_timestamp(p_occurred),'grants_authority',false);
  insert into agents.residency_event
    (id,realm_id,residency_id,edge_id,sequence,previous_digest,state,generation,reason,
     event_digest,event_body,occurred_at)
    values(event_id,p_realm,p_residency,p_edge,seq,
      case when seq=1 then null else previous.event_digest end,p_state,p_generation,p_reason,
      models.capability_runtime_jsonb_digest(body),body,p_occurred);
end $$;
revoke all on function agents.append_residency_event(uuid,uuid,uuid,text,integer,text,timestamptz)
from public;

create function agents.register_runtime_residency(
  p_id uuid,p_realm uuid,p_edge uuid,p_snapshot uuid,p_session text,p_created timestamptz
) returns void language plpgsql security definer
set search_path=pg_catalog,agents,core as $$
begin
  if p_realm is distinct from core.current_realm_id() then
    raise exception 'cross-realm residency register denied' using errcode='42501'; end if;
  if btrim(p_session)='' then
    raise exception 'runtime session ref bos olamaz' using errcode='23514'; end if;
  perform 1 from agents.spawn_edge where realm_id=p_realm and id=p_edge for update;
  if not exists(select 1 from agents.assignment_runtime_snapshot snapshot
      join agents.spawn_edge edge on edge.realm_id=snapshot.realm_id and edge.id=snapshot.edge_id
      where snapshot.realm_id=p_realm and snapshot.id=p_snapshot and snapshot.edge_id=p_edge
        and edge.status not in ('completed','failed','cancelled')) then
    raise exception 'residency snapshot/edge binding gecersiz' using errcode='23514'; end if;
  insert into agents.runtime_residency
    (id,realm_id,edge_id,runtime_snapshot_id,state,generation,runtime_session_ref,
     last_seen_at,state_changed_at,created_at)
    values(p_id,p_realm,p_edge,p_snapshot,'loaded',1,p_session,p_created,p_created,p_created);
  perform agents.append_residency_event(p_realm,p_id,p_edge,'loaded',1,null,p_created);
end $$;

create function agents.transition_runtime_residency(
  p_realm uuid,p_edge uuid,p_state text,p_occurred timestamptz,p_reason text
) returns boolean language plpgsql security definer
set search_path=pg_catalog,agents,core as $$
declare current record; declare assignment_id uuid; declare edge_status text;
begin
  if p_realm is distinct from core.current_realm_id() then
    raise exception 'cross-realm residency transition denied' using errcode='42501'; end if;
  select * into current from agents.runtime_residency
    where realm_id=p_realm and edge_id=p_edge for update;
  if not found then raise exception 'runtime residency bulunamadi' using errcode='P0002'; end if;
  if current.state=p_state then return false; end if;
  if not ((current.state='loaded' and p_state in ('idle','evicted','closing','dead'))
    or (current.state='idle' and p_state in ('evicted','closing','dead'))
    or (current.state='closing' and p_state='dead')
    or (current.state='evicted' and p_state='dead')) then
    raise exception 'runtime residency state gecisi gecersiz' using errcode='23514'; end if;
  if (p_state='dead') is distinct from (p_reason is not null and btrim(p_reason)<>'') then
    raise exception 'dead residency exact reason ister' using errcode='23514'; end if;
  if p_occurred<current.state_changed_at then
    raise exception 'residency zamani geriye gidemez' using errcode='23514'; end if;
  if p_state='dead' then
    select child_assignment_id,status into assignment_id,edge_status from agents.spawn_edge
      where realm_id=p_realm and id=p_edge;
    if edge_status not in ('completed','failed','cancelled') then
      update agents.assignment set status='recovery-required',terminal_at=null
        where realm_id=p_realm and id=assignment_id
          and status not in ('completed','failed','cancelled');
    end if;
  end if;
  update agents.runtime_residency set state=p_state,
    runtime_session_ref=case when p_state in ('evicted','dead') then null
      else runtime_session_ref end,
    dead_reason=case when p_state='dead' then p_reason else null end,
    last_seen_at=p_occurred,state_changed_at=p_occurred
    where realm_id=p_realm and edge_id=p_edge;
  perform agents.append_residency_event(p_realm,current.id,p_edge,p_state,current.generation,
    p_reason,p_occurred);
  return true;
end $$;

create function agents.reload_runtime_residency(
  p_realm uuid,p_edge uuid,p_current_environment text,p_current_route uuid,
  p_current_provider uuid,p_session text,p_requested timestamptz,p_request_digest text,
  p_request_body jsonb
) returns table(accepted boolean,state text,generation integer,reason text)
language plpgsql security definer set search_path=pg_catalog,agents,runtime,models,core as $$
declare residency record; declare snapshot record; declare edge record; declare run record;
declare route record; declare provider record; declare environment record; declare why text;
declare attempt_id uuid:=gen_random_uuid(); declare next_generation integer; declare prior record;
begin
  if p_realm is distinct from core.current_realm_id() then
    raise exception 'cross-realm residency reload denied' using errcode='42501'; end if;
  if models.capability_runtime_jsonb_digest(p_request_body)<>p_request_digest
    or (select count(*) from jsonb_object_keys(p_request_body))<>9
    or p_request_body->>'schema'<>'zekam-agent-reload-request/v1'
    or p_request_body->>'realm_id'<>p_realm::text
    or p_request_body->>'edge_id'<>p_edge::text
    or p_request_body->>'current_environment_snapshot_digest'<>p_current_environment
    or p_request_body->>'current_route_decision_id'<>p_current_route::text
    or p_request_body->>'current_provider_binding_id'<>p_current_provider::text
    or p_request_body->>'runtime_session_ref'<>p_session
    or (p_request_body->>'requested_at')::timestamptz<>p_requested
    or (p_request_body->>'grants_authority')::boolean then
    raise exception 'reload request body/digest drift' using errcode='23514'; end if;
  if btrim(p_session)='' or p_requested>statement_timestamp()
    or p_requested<statement_timestamp()-interval '30 seconds' then
    raise exception 'reload session/temporal provenance gecersiz' using errcode='23514'; end if;
  select * into residency from agents.runtime_residency
    where realm_id=p_realm and edge_id=p_edge for update;
  if not found then raise exception 'runtime residency bulunamadi' using errcode='P0002'; end if;
  if p_requested<residency.state_changed_at then
    raise exception 'reload request residency durumundan eski' using errcode='23514'; end if;
  select attempt.accepted,attempt.reason,attempt.resulting_generation into prior
    from agents.reload_attempt attempt
    where attempt.realm_id=p_realm and attempt.request_digest=p_request_digest;
  if found then
    return query select prior.accepted,
      case when prior.accepted then 'loaded' else residency.state end,
      prior.resulting_generation,prior.reason;
    return;
  end if;
  select * into snapshot from agents.assignment_runtime_snapshot
    where realm_id=p_realm and id=residency.runtime_snapshot_id;
  select status,root_id into edge from agents.spawn_edge
    where realm_id=p_realm and id=p_edge;
  select rrun.* into run from agents.graph_root root join runtime.execution_run rrun
    on rrun.realm_id=root.realm_id and rrun.id=root.run_id
    where root.realm_id=p_realm and root.id=edge.root_id;
  select d.status,d.primary_model_id,d.evidence_digest,t.expires_at,d.role,d.target_layer,
    d.project_id,d.workload,d.technology,d.decided_at into route
    from models.model_route_decision d join models.execution_target_snapshot t
      on t.realm_id=d.realm_id and t.id=d.execution_target_id
    where d.realm_id=p_realm and d.id=p_current_route;
  select model_id,provider_ref,operation,binding_digest,captured_at,expires_at into provider
    from models.provider_binding_snapshot where realm_id=p_realm and id=p_current_provider;
  select permission_profile_digest,config_effective_digest,source_revision,expires_at into environment
    from runtime.execution_environment_snapshot
    where realm_id=p_realm and snapshot_digest=p_current_environment;
  if residency.state<>'evicted' then why:='not-evicted';
  elsif edge.status in ('completed','failed','cancelled') then why:='child-terminal';
  elsif not exists(select 1 from agents.assignment assignment
      where assignment.realm_id=p_realm and assignment.id=snapshot.assignment_id
        and assignment.role=snapshot.role
        and assignment.status not in ('completed','failed','cancelled')) then
    why:='assignment-drift';
  elsif run.state<>'active' or run.deadline<=statement_timestamp()
    or run.deadline<=p_requested or run.source_revision<>snapshot.source_revision
    or run.policy_digest<>snapshot.policy_digest then why:='source-policy-drift';
  elsif p_current_route<>snapshot.route_decision_id or route.status<>'selected'
    or route.primary_model_id<>snapshot.model_id
    or route.evidence_digest<>snapshot.route_decision_digest
    or route.expires_at<=p_requested or route.expires_at<=statement_timestamp()
    or exists(select 1 from models.model_route_decision latest
      where latest.realm_id=p_realm and latest.status='selected'
        and latest.role=route.role and latest.target_layer=route.target_layer
        and latest.project_id is not distinct from route.project_id
        and latest.workload is not distinct from route.workload
        and latest.technology is not distinct from route.technology
        and (latest.decided_at,latest.id)>(route.decided_at,p_current_route))
    then why:='route-drift';
  elsif p_current_provider<>snapshot.provider_binding_id
    or provider.model_id<>snapshot.model_id
    or provider.binding_digest<>snapshot.provider_binding_digest
    or provider.expires_at<=p_requested or provider.expires_at<=statement_timestamp()
    or exists(select 1 from models.provider_binding_snapshot latest
      where latest.realm_id=p_realm and latest.model_id=provider.model_id
        and latest.provider_ref=provider.provider_ref and latest.operation=provider.operation
        and (latest.captured_at,latest.id)>(provider.captured_at,p_current_provider))
    then why:='provider-drift';
  elsif environment.permission_profile_digest<>snapshot.permission_profile_digest
    or environment.config_effective_digest<>snapshot.config_effective_digest
    or environment.source_revision<>snapshot.source_revision
    or environment.expires_at<=p_requested or environment.expires_at<=statement_timestamp()
    or not exists(select 1 from runtime.environment_probe_evidence probe
      where probe.realm_id=p_realm
        and probe.sticky_snapshot_digest=snapshot.environment_snapshot_digest
        and probe.current_snapshot_digest=p_current_environment
        and cardinality(probe.drift_dimensions)=0
        and probe.checked_at<=p_requested
        and probe.checked_at>=p_requested-interval '5 minutes'
        and probe.checked_at>=statement_timestamp()-interval '5 minutes'
        and probe.id=(select latest.id from runtime.environment_probe_evidence latest
          where latest.realm_id=probe.realm_id
            and latest.sticky_snapshot_digest=probe.sticky_snapshot_digest
          order by latest.checked_at desc,latest.id desc limit 1)) then why:='environment-drift';
  end if;
  next_generation:=residency.generation+case when why is null then 1 else 0 end;
  if why is null then
    update agents.runtime_residency set state='loaded',generation=next_generation,
      runtime_session_ref=p_session,last_seen_at=p_requested,state_changed_at=p_requested
      where realm_id=p_realm and edge_id=p_edge;
    perform agents.append_residency_event(p_realm,residency.id,p_edge,'loaded',
      next_generation,null,p_requested);
  end if;
  insert into agents.reload_attempt
    (id,realm_id,residency_id,edge_id,stored_snapshot_id,
     current_environment_snapshot_digest,current_route_decision_id,
     current_provider_binding_id,accepted,reason,resulting_generation,request_digest,
     request_body,attempted_at)
    values(attempt_id,p_realm,residency.id,p_edge,snapshot.id,p_current_environment,
      p_current_route,p_current_provider,why is null,why,next_generation,p_request_digest,
      p_request_body,p_requested);
  return query select why is null,case when why is null then 'loaded' else residency.state end,
    next_generation,why;
end $$;

create function agents.publish_residency_event() returns trigger language plpgsql
security invoker set search_path=pg_catalog,agents,app_server as $$
begin
  perform app_server.publish_notification(new.realm_id,gen_random_uuid(),
    'agent.residency.changed',jsonb_build_object('edge_id',new.edge_id::text,
      'state',new.state,'generation',new.generation,'event_digest',new.event_digest),
    new.occurred_at);
  return new;
end $$;
create trigger residency_event_publish after insert on agents.residency_event
for each row execute function agents.publish_residency_event();

create trigger assignment_runtime_snapshot_no_mutation before update or delete
on agents.assignment_runtime_snapshot for each statement execute function core.deny_mutation();
create trigger residency_event_no_mutation before update or delete on agents.residency_event
for each statement execute function core.deny_mutation();
create trigger reload_attempt_no_mutation before update or delete on agents.reload_attempt
for each statement execute function core.deny_mutation();
create trigger runtime_residency_no_delete before delete on agents.runtime_residency
for each statement execute function core.deny_mutation();

do $$ declare target text; begin foreach target in array array[
  'agents.assignment_runtime_snapshot','agents.runtime_residency',
  'agents.residency_event','agents.reload_attempt'
] loop
  execute format('alter table %s enable row level security',target);
  execute format('alter table %s force row level security',target);
  execute format('create policy scope_select on %s for select using(realm_id=core.current_realm_id())',target);
  execute format('create policy scope_insert on %s for insert with check(realm_id=core.current_realm_id())',target);
end loop; end $$;
grant select,insert on agents.assignment_runtime_snapshot to zekam_app;
grant select on agents.runtime_residency,agents.residency_event,agents.reload_attempt to zekam_app;
revoke all on function agents.register_runtime_residency(uuid,uuid,uuid,uuid,text,timestamptz)
  from public;
revoke all on function agents.transition_runtime_residency(uuid,uuid,text,timestamptz,text)
  from public;
revoke all on function agents.reload_runtime_residency(uuid,uuid,text,uuid,uuid,text,
  timestamptz,text,jsonb) from public;
grant execute on function agents.register_runtime_residency(uuid,uuid,uuid,uuid,text,timestamptz)
  to zekam_app;
grant execute on function agents.transition_runtime_residency(uuid,uuid,text,timestamptz,text)
  to zekam_app;
grant execute on function agents.reload_runtime_residency(uuid,uuid,text,uuid,uuid,text,
  timestamptz,text,jsonb) to zekam_app;
